config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/spacetelescope/PyFITS:
      branch: master
      repo: https://github.com/spacetelescope/PyFITS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/spacetelescope/PyFITS git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-cinnamon-dragonfly.sh
        container: qc.acc_skanky-eggplant-bear
  QC.Doc:
    repos:
      github.com/spacetelescope/PyFITS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cinnamon-manatee.sh
        container: qc.doc_boozy-smalt-wallaby
      github.com/spacetelescope/PyFITS git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-indigo-retriever.sh
        container: qc.doc_hasty-mauve-numbat
      github.com/spacetelescope/PyFITS restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-sapphire-vulture.sh
        container: qc.doc_squirrely-vermilion-wildebeest
  QC.Lic:
    repos:
      github.com/spacetelescope/PyFITS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-champagne-sparrow.sh
        container: qc.lic_lousy-aqua-bonobo
  QC.Sec:
    repos:
      github.com/spacetelescope/PyFITS bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-periwinkle-bird.sh
        container: qc.sec_cranky-bistre-cichlid
  QC.Sty:
    repos:
      github.com/spacetelescope/PyFITS flake8:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-ivory-bongo.sh
        container: qc.sty_sickly-corn-salamander
  QC.Ver:
    repos:
      github.com/spacetelescope/PyFITS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-mauve-fish.sh
        container: qc.ver_sloppy-sepia-molly
timeout: 5400
